name: Generate Datas

on:
  schedule: # execute a cada 12 horas
    - cron: "*/12 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs para atualizar dados
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Gerar animação da serpente
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: hwoxan # Altere para o seu nome de usuário do GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Atualizar GitHub Pages
      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
